{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moment-tally-server.adminSecretName" . }}
  labels:
    {{- include "moment-tally-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | quote }}
{{- end }}
